apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "isplitapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: '{{ include "isplitapp.fullname" . }}-tls'
  dnsNames:
    - "{{ .Values.appDomain }}"
    - "{{ .Values.apiDomain }}"
    - "{{ .Values.otlpDomain }}"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer