apiVersion: v1
kind: Service
metadata:
  name: {{ include "isplitapp.fullname" . }}
  labels:
    {{- include "isplitapp.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "isplitapp.selectorLabels" . | nindent 4 }}