apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: isplitapp
  namespace: isplitapp
spec:
  secretName: isplitapp-tls        
  dnsNames:
    - "isplitapp.bdgn.me"
    - "api-isplitapp.bdgn.me"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer