apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: isplitapp

# setting labels
#
labels:
  - pairs:
      kubernetes.io/name: isplitapp
      kubernetes.io/instance: isplitapp
      managed-by: kustomize
    includeSelectors: true 

# setting annotations
#
commonAnnotations:
  version: "latest"

secretGenerator:
  - name: isplitapp
    envs:
      - ./.env.secret

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - configmap-fbkey.secret.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
