apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: 'isplit-backup'
  namespace: isplitapp
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: pg-isplit
  immediate: true