apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "isplitapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isplitapp.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.appDomain }}`) || Host(`{{ .Values.apiDomain }}`)
      kind: Rule
      services:
        - name: {{ include "isplitapp.fullname" . }}
          port: {{ .Values.app.port }}
  tls:
    secretName: '{{ include "isplitapp.fullname" . }}-tls'