apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: "argoproj.io"
      version: "v1alpha1"
      kind: "Application"
      name: "sailingapp"
    patch: |-
      [
        {
          "add": "replace",
          "path": "/spec/source/helm/valueFiles",
          "value": "proxmox.values.yaml"
        }
      ]

  - target:
      group: "postgresql.cnpg.io"
      version: "v1"
      kind: "Cluster"
      name: "pg-isplit"
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/backup/barmanObjectStore/destinationPath",
          "value": "s3://ib.pg-backup/pg-proxmox"
        },
        {
          "op": "replace",
          "path": "/spec/externalClusters/0/barmanObjectStore/destinationPath",
          "value": "s3://ib.pg-backup/pg-proxmox-backup"
        }
      ]