apiVersion: apps/v1
kind: Deployment
metadata:
  name: isplit-frontend
  labels:
    app: isplit-frontend
    tier: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: isplit-frontend
  
  template:
    metadata:
      labels:
        app: isplit-frontend
        tier: frontend
    
    spec:
      containers:
      - name: frontend
        image: isplit/frontend:latest
        ports:
        - containerPort: 80
        
        # Runtime configuration via environment variables
        env:
        - name: BACKEND_URL
          value: "https://api.isplit.com"
          # Alternative: from ConfigMap
          # valueFrom:
          #   configMapKeyRef:
          #     name: isplit-config
          #     key: backend-url
        
        # Alternative: from Secret (for sensitive URLs)
        # - name: BACKEND_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: isplit-secrets
        #       key: backend-url
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: isplit-frontend-service
  labels:
    app: isplit-frontend

spec:
  selector:
    app: isplit-frontend
  
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isplit-frontend-ingress
  labels:
    app: isplit-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  tls:
  - hosts:
    - app.isplit.com
    secretName: isplit-frontend-tls
  
  rules:
  - host: app.isplit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: isplit-frontend-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: isplit-config
  labels:
    app: isplit

data:
  backend-url: "https://api.isplit.com"
  # Add other configuration values here
  # environment: "production"
  # feature-flags: "new-ui=true,beta-features=false"
