apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
secretGenerator:
  - name: isplitapp
    envs:
      - ./.env.secret
    behavior: merge


patches:
  - deployment-patch.yaml
  - ingress-patch.yaml

