name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-all:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: isplitapp-core  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set version var
      run: |
        echo "hash=$(echo "${{github.sha}}" | cut -c 1-7)" >> $GITHUB_ENV
        echo "version=1.0.${{github.run_number}}" >> $GITHUB_ENV

    - name: generate semver
      uses: paulhatch/semantic-version@v5.1.0
      id: semver
      with:
        tag_prefix: "v"
        major_pattern: "[MAJOR]"
        minor_pattern: "[MINOR]"
        search_commit_body: true
        bump_each_commit: true
        version_format: ${major}.${minor}.${patch}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push production
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #file: ./isplitapp-core/core/Dockerfile
        push: true
        tags: ilaverlin/isplitapp-full:latest, ilaverlin/isplitapp-full:${{ steps.semver.outputs.version }}
        build-args: |
          BUILD_ENV=production
          VERSION=${{ steps.semver.outputs.version }}


    - name: Build and push dev
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #file: ./isplitapp-core/core/Dockerfile
        push: true
        tags: ilaverlin/isplitapp-full:edge, ilaverlin/isplitapp-full:${{ steps.semver.outputs.version }}-${{ env.hash }}
        build-args: |
          BUILD_ENV=development
          VERSION=${{ steps.semver.outputs.version }}-dev.${{github.run_number}}+${{ env.hash }}
          BUILD_CONFIGURATION=Debug
  