name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-net:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: isplitapp-core  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set version var
      run: |
        echo "version=1.0.${{github.run_number}}-$(echo "${{github.sha}}" | cut -c 1-7)" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push production
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #file: ./isplitapp-core/core/Dockerfile
        push: true
        tags: ilaverlin/isplitapp-full-prod:latest,ilaverlin/isplitapp-full:${{ env.version }}
        build-args: |
          BUILD_ENV=production
          VERSION=${{ env.version }}

    - name: Build and push dev
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #file: ./isplitapp-core/core/Dockerfile
        push: true
        tags: ilaverlin/isplitapp-full-dev:latest,ilaverlin/isplitapp-full:${{ env.version }}
        build-args: |
          BUILD_ENV=development
          VERSION=${{ env.version }}
  